

from BaseClasses import ItemClassification, Item
from typing import NamedTuple, Dict

class DMW2003Item(Item):
    game: str = "Digimon World 2003"

class ItemData(NamedTuple):
    id: int
    classification: ItemClassification

ACTUAL_ITEMS: Dict[str, ItemData] = {
	"Tree Boots": ItemData(4, ItemClassification.useful),
	"Fishing Pole": ItemData(5, ItemClassification.useful),
	"Agumon DDNA": ItemData(6, ItemClassification.useful),
	"El Dorado ID": ItemData(8, ItemClassification.skip_balancing),
	"Smelly Herb": ItemData(13, ItemClassification.progression),
	"TNT Chip": ItemData(14, ItemClassification.progression),
	"Agumon Suit": ItemData(15, ItemClassification.progression),
	"DE Sincerity": ItemData(16, ItemClassification.progression),
	"DE Knowledge": ItemData(17, ItemClassification.progression),
	"Asuka Trophy": ItemData(18, ItemClassification.filler),
	"Kotemon DDNA": ItemData(19, ItemClassification.useful),
	"Sun Trophy": ItemData(20, ItemClassification.filler),
	"Sepik Mask": ItemData(21, ItemClassification.progression),
	"Blue ID Pass": ItemData(22, ItemClassification.progression),
	"Red ID Pass": ItemData(23, ItemClassification.progression),
	"White ID Pass": ItemData(24, ItemClassification.progression),
	"Black ID Pass": ItemData(25, ItemClassification.progression),
	# "セイリュウÁタグ": ItemData(26, ItemClassification.filler),
	# "スザクÁタグ": ItemData(27, ItemClassification.filler),
	# "ビャッコÁタグ": ItemData(28, ItemClassification.filler),
	# "ゲンブÁタグ": ItemData(29, ItemClassification.filler),
	# "チンロンÁタグ": ItemData(30, ItemClassification.filler),
	# "スーツェイÁタグ": ItemData(31, ItemClassification.filler),
	# "バイフーÁタグ": ItemData(32, ItemClassification.filler),
	# "シェンウーÁタグ": ItemData(33, ItemClassification.filler),
	"Guilmon DDNA": ItemData(34, ItemClassification.useful),
	"Veemon DDNA": ItemData(35, ItemClassification.useful),
	"Koc Trophy": ItemData(36, ItemClassification.filler),
	"Platinum Card": ItemData(37, ItemClassification.useful),
	"Renamon DDNA": ItemData(38, ItemClassification.useful),
	"Patamon DDNA": ItemData(39, ItemClassification.useful),
	"Silver ID": ItemData(40, ItemClassification.useful),
	"Gold ID": ItemData(41, ItemClassification.useful),
	"Platinum ID": ItemData(42, ItemClassification.useful),
	"Power Charge": ItemData(43, ItemClassification.filler),
	"Super Charge": ItemData(44, ItemClassification.filler),
	"Ultra Charge": ItemData(45, ItemClassification.filler),
	"Max Charge": ItemData(46, ItemClassification.filler),
	"HP Chip": ItemData(47, ItemClassification.filler),
	"MP Chip": ItemData(48, ItemClassification.filler),
	"Power Chip": ItemData(49, ItemClassification.filler),
	"Armor Chip": ItemData(50, ItemClassification.filler),
	"Mind Chip": ItemData(51, ItemClassification.filler),
	"Wisdom Chip": ItemData(52, ItemClassification.filler),
	"Boost Chip": ItemData(53, ItemClassification.filler),
	"Charisma Chip": ItemData(54, ItemClassification.filler),
	"Fire Chip": ItemData(55, ItemClassification.filler),
	"Water Chip": ItemData(56, ItemClassification.filler),
	"Ice Chip": ItemData(57, ItemClassification.filler),
	"Wind Chip": ItemData(58, ItemClassification.filler),
	"Thunder Chip": ItemData(59, ItemClassification.filler),
	"Metal Chip": ItemData(60, ItemClassification.filler),
	"Devil Chip": ItemData(61, ItemClassification.filler),
	"Train Chip 1": ItemData(62, ItemClassification.filler),
	"Train Chip 2": ItemData(63, ItemClassification.filler),
	"Train Chip 3": ItemData(64, ItemClassification.filler),
	"Train Chip V": ItemData(65, ItemClassification.filler),
	"Antidote Disk": ItemData(66, ItemClassification.filler),
	"Revive Disk": ItemData(67, ItemClassification.filler),
	"Sober Disk": ItemData(68, ItemClassification.filler),
	"Energy Disk": ItemData(69, ItemClassification.filler),
	"Life Disk": ItemData(70, ItemClassification.filler),
	"Life Plug": ItemData(71, ItemClassification.filler),
	"Mach Plug": ItemData(72, ItemClassification.filler),
	"Power Plug": ItemData(73, ItemClassification.filler),
	"Guard Plug": ItemData(74, ItemClassification.filler),
	"Aura Plug": ItemData(75, ItemClassification.filler),
	"DV Plug": ItemData(76, ItemClassification.filler),
	"Flame Field": ItemData(77, ItemClassification.filler),
	"Water Field": ItemData(78, ItemClassification.filler),
	"Ice Field": ItemData(79, ItemClassification.filler),
	"Wind Field": ItemData(80, ItemClassification.filler),
	"Thunder Field": ItemData(81, ItemClassification.filler),
	"Machine Field": ItemData(82, ItemClassification.filler),
	"Dark Field": ItemData(83, ItemClassification.filler),
	"Unknown Field": ItemData(84, ItemClassification.filler),
	"Crimson Cable": ItemData(85, ItemClassification.filler),
	"Chaos Wave": ItemData(86, ItemClassification.filler),
	"Charm Gas": ItemData(87, ItemClassification.filler),
	"Cursed Puppet": ItemData(88, ItemClassification.filler),
	"Spider Web": ItemData(89, ItemClassification.filler),
	"TNT Ball": ItemData(90, ItemClassification.filler),
	"Booster 01a": ItemData(91, ItemClassification.filler),
	"Short Sword": ItemData(92, ItemClassification.filler),
	"Zanden Sword": ItemData(93, ItemClassification.filler),
	"Crimson Blade": ItemData(94, ItemClassification.filler),
	"Mighty Blade": ItemData(95, ItemClassification.filler),
	"Shiratorimaru": ItemData(96, ItemClassification.filler),
	"Shine Blade": ItemData(97, ItemClassification.filler),
	"Ronin Blade": ItemData(98, ItemClassification.filler),
	"Onimaru": ItemData(99, ItemClassification.filler),
	"Tenjinmaru": ItemData(100, ItemClassification.filler),
	"Fuujin Blade": ItemData(101, ItemClassification.filler),
	"Rusty Katana": ItemData(102, ItemClassification.filler),
	"Kotetsu": ItemData(103, ItemClassification.filler),
	"Masamune": ItemData(104, ItemClassification.filler),
	"Muramasa": ItemData(105, ItemClassification.filler),
	"Leather Glove": ItemData(106, ItemClassification.filler),
	"Cat Glove": ItemData(107, ItemClassification.filler),
	"Iron Glove": ItemData(108, ItemClassification.filler),
	"Needle Glove": ItemData(109, ItemClassification.filler),
	"Power Arm": ItemData(110, ItemClassification.filler),
	"Tiger Glove": ItemData(111, ItemClassification.filler),
	"Wild Glove": ItemData(112, ItemClassification.filler),
	"Kaiser Fist": ItemData(113, ItemClassification.filler),
	"Tempest Arm": ItemData(114, ItemClassification.filler),
	"Raijin Fist": ItemData(115, ItemClassification.filler),
	"Rusty Glove": ItemData(116, ItemClassification.filler),
	"Zodiac": ItemData(117, ItemClassification.filler),
	"Prominence": ItemData(118, ItemClassification.filler),
	"Super Nova": ItemData(119, ItemClassification.filler),
	"Handgun": ItemData(120, ItemClassification.filler),
	"Machinegun": ItemData(121, ItemClassification.filler),
	"Shotgun": ItemData(122, ItemClassification.filler),
	"Psycho Blaster": ItemData(123, ItemClassification.filler),
	"Sniper Cannon": ItemData(124, ItemClassification.filler),
	"Cluster Cannon": ItemData(125, ItemClassification.filler),
	"Laser Cannon": ItemData(126, ItemClassification.filler),
	"Suijin Cannon": ItemData(127, ItemClassification.filler),
	"Rusty Rifle": ItemData(128, ItemClassification.filler),
	"Justice": ItemData(129, ItemClassification.filler),
	"Judgment": ItemData(130, ItemClassification.filler),
	"Punishment": ItemData(131, ItemClassification.filler),
	"Wooden Rod": ItemData(132, ItemClassification.filler),
	"Magician Rod": ItemData(133, ItemClassification.filler),
	"Bone Rod": ItemData(134, ItemClassification.filler),
	"Misty Rod": ItemData(135, ItemClassification.filler),
	"Divine Rod": ItemData(136, ItemClassification.filler),
	"Yin Yang Wand": ItemData(137, ItemClassification.filler),
	"Khakkhara": ItemData(138, ItemClassification.filler),
	"Crystal Rod": ItemData(139, ItemClassification.filler),
	"Millenium": ItemData(140, ItemClassification.filler),
	"Old Wand": ItemData(141, ItemClassification.filler),
	"Twinkle": ItemData(142, ItemClassification.filler),
	"Immaculate": ItemData(143, ItemClassification.filler),
	"Eternally": ItemData(144, ItemClassification.filler),
	"Wolf Fang": ItemData(145, ItemClassification.filler),
	"Ghost Fang": ItemData(146, ItemClassification.filler),
	"Cerberus Fang": ItemData(147, ItemClassification.filler),
	"Evil Fang": ItemData(148, ItemClassification.filler),
	"Hazard Fang": ItemData(149, ItemClassification.filler),
	"Saber Fang": ItemData(150, ItemClassification.filler),
	"Venom Fang": ItemData(151, ItemClassification.filler),
	"Belial Fang": ItemData(152, ItemClassification.filler),
	"Old Claw": ItemData(153, ItemClassification.filler),
	"Vanquish": ItemData(154, ItemClassification.filler),
	"Destruction": ItemData(155, ItemClassification.filler),
	"Invincible": ItemData(156, ItemClassification.filler),
	"Dagger": ItemData(157, ItemClassification.filler),
	"Shishioumaru": ItemData(158, ItemClassification.filler),
	"Long Sword": ItemData(159, ItemClassification.filler),
	"Shamshir": ItemData(160, ItemClassification.filler),
	"Wing Sword": ItemData(161, ItemClassification.filler),
	"Kulon Sword": ItemData(162, ItemClassification.filler),
	"Brave Sword": ItemData(163, ItemClassification.filler),
	"Excalibur": ItemData(164, ItemClassification.filler),
	"Grey Sword": ItemData(165, ItemClassification.filler),
	"Fenrir Sword": ItemData(166, ItemClassification.filler),
	"Bamboo Spear": ItemData(167, ItemClassification.filler),
	"Spear": ItemData(168, ItemClassification.filler),
	"Fairy Tale": ItemData(169, ItemClassification.filler),
	"Partisan": ItemData(170, ItemClassification.filler),
	"Divine Lance": ItemData(171, ItemClassification.filler),
	"Trent": ItemData(172, ItemClassification.filler),
	"Vampire Lance": ItemData(173, ItemClassification.filler),
	"Royal Spear": ItemData(174, ItemClassification.filler),
	"Orochi Spear": ItemData(175, ItemClassification.filler),
	"Claymore": ItemData(176, ItemClassification.filler),
	"Chain Saw": ItemData(177, ItemClassification.filler),
	"Zweihander": ItemData(178, ItemClassification.filler),
	"Flamberge": ItemData(179, ItemClassification.filler),
	"Rock Breaker": ItemData(180, ItemClassification.filler),
	"Atlas Buster": ItemData(181, ItemClassification.filler),
	"Gulf Sword": ItemData(182, ItemClassification.filler),
	"Halberd": ItemData(183, ItemClassification.filler),
	"Naginata": ItemData(184, ItemClassification.filler),
	"Berdys": ItemData(185, ItemClassification.filler),
	"Soul Chopper": ItemData(186, ItemClassification.filler),
	"Ryuuzanmaru": ItemData(187, ItemClassification.filler),
	"Gaea Halberd": ItemData(188, ItemClassification.filler),
	"Omega Halberd": ItemData(189, ItemClassification.filler),
	"Long Bow": ItemData(190, ItemClassification.filler),
	"Shuriken": ItemData(191, ItemClassification.filler),
	"Crossbow": ItemData(192, ItemClassification.filler),
	"Angel Bow": ItemData(193, ItemClassification.filler),
	"Raven Bow": ItemData(194, ItemClassification.filler),
	"Lightning Bow": ItemData(195, ItemClassification.filler),
	"Seraphic Bow": ItemData(196, ItemClassification.filler),
	"Garuru Cannon": ItemData(197, ItemClassification.filler),
	"Positron Cannon": ItemData(198, ItemClassification.filler),
	"Mini Guard": ItemData(199, ItemClassification.filler),
	"Pulse Guard": ItemData(200, ItemClassification.filler),
	"Metal Guard": ItemData(201, ItemClassification.filler),
	"Mighty Guard": ItemData(202, ItemClassification.filler),
	"Dramon Guard": ItemData(203, ItemClassification.filler),
	"Mach Guard": ItemData(204, ItemClassification.filler),
	"Mega Guard": ItemData(205, ItemClassification.filler),
	"Deus Guard": ItemData(206, ItemClassification.filler),
	"Metal Horn": ItemData(207, ItemClassification.filler),
	"Drill Horn": ItemData(208, ItemClassification.filler),
	"Kabuteri Horn": ItemData(209, ItemClassification.filler),
	"Shock Horn": ItemData(210, ItemClassification.filler),
	"Dramon Horn": ItemData(211, ItemClassification.filler),
	"Scissor Horn": ItemData(212, ItemClassification.filler),
	"Trihorn": ItemData(213, ItemClassification.filler),
	"Glorious Horn": ItemData(214, ItemClassification.filler),
	"Bandanna": ItemData(215, ItemClassification.filler),
	"Sun Visor": ItemData(216, ItemClassification.filler),
	"Baseball Cap": ItemData(217, ItemClassification.filler),
	"School Cap": ItemData(218, ItemClassification.filler),
	"Wool Cap": ItemData(219, ItemClassification.filler),
	"Kung Fu Cap": ItemData(220, ItemClassification.filler),
	"Yin Yang Hat": ItemData(221, ItemClassification.filler),
	"Sniper Goggle": ItemData(222, ItemClassification.filler),
	"Night Vision": ItemData(223, ItemClassification.filler),
	"Beret": ItemData(224, ItemClassification.filler),
	"Red Cap": ItemData(225, ItemClassification.filler),
	"Ribbon": ItemData(226, ItemClassification.filler),
	"Cat Ears": ItemData(227, ItemClassification.filler),
	"Headband": ItemData(228, ItemClassification.filler),
	"Mythril Crown": ItemData(229, ItemClassification.filler),
	"Magical Crown": ItemData(230, ItemClassification.filler),
	"Shaman Mask": ItemData(231, ItemClassification.filler),
	"Divine Crown": ItemData(232, ItemClassification.filler),
	"Angel Ring": ItemData(233, ItemClassification.filler),
	"Royal Crown": ItemData(234, ItemClassification.filler),
	"Goddess Crown": ItemData(235, ItemClassification.filler),
	"Hide Helmet": ItemData(236, ItemClassification.filler),
	"Tin Helmet": ItemData(237, ItemClassification.filler),
	"Iron Helmet": ItemData(238, ItemClassification.filler),
	"Knight Helmet": ItemData(239, ItemClassification.filler),
	"Wing Helmet": ItemData(240, ItemClassification.filler),
	"Kulon Helmet": ItemData(241, ItemClassification.filler),
	"Wild Helmet": ItemData(242, ItemClassification.filler),
	"Ronin Helmet": ItemData(243, ItemClassification.filler),
	"Brave Helmet": ItemData(244, ItemClassification.filler),
	"Hazard Helmet": ItemData(245, ItemClassification.filler),
	"D-Tama Helmet": ItemData(246, ItemClassification.filler),
	"Matrix Helmet": ItemData(247, ItemClassification.filler),
	"Mugen Helmet": ItemData(248, ItemClassification.filler),
	"Leather Coat": ItemData(249, ItemClassification.filler),
	"Gym Suit": ItemData(250, ItemClassification.filler),
	"Priest Robe": ItemData(251, ItemClassification.filler),
	"Rubber Suit": ItemData(252, ItemClassification.filler),
	"Dark Cloak": ItemData(253, ItemClassification.filler),
	"Down Jacket": ItemData(254, ItemClassification.filler),
	"Divine Robe": ItemData(255, ItemClassification.filler),
	"Sniper Suit": ItemData(256, ItemClassification.filler),
	"Yin Yang Suit": ItemData(257, ItemClassification.filler),
	"Wild Suit": ItemData(258, ItemClassification.filler),
	"Body Armor": ItemData(259, ItemClassification.filler),
	"Mirage Robe": ItemData(260, ItemClassification.filler),
	"King's Mantle": ItemData(261, ItemClassification.filler),
	"Leather Mail": ItemData(262, ItemClassification.filler),
	"Tin Mail": ItemData(263, ItemClassification.filler),
	"Iron Armor": ItemData(264, ItemClassification.filler),
	"Digitama Mail": ItemData(265, ItemClassification.filler),
	"Dark Armor": ItemData(266, ItemClassification.filler),
	"Kulon Armor": ItemData(267, ItemClassification.filler),
	"Dramon Armor": ItemData(268, ItemClassification.filler),
	"Ronin Armor": ItemData(269, ItemClassification.filler),
	"Hazard Armor": ItemData(270, ItemClassification.filler),
	"Brave Armor": ItemData(271, ItemClassification.filler),
	"Beam Armor": ItemData(272, ItemClassification.filler),
	"Misty Armor": ItemData(273, ItemClassification.filler),
	"Crimson Mail": ItemData(274, ItemClassification.filler),
	"Buckler": ItemData(275, ItemClassification.filler),
	"Tin Shield": ItemData(276, ItemClassification.filler),
	"Iron Shield": ItemData(277, ItemClassification.filler),
	"Knight Shield": ItemData(278, ItemClassification.filler),
	"Guard Barrier": ItemData(279, ItemClassification.filler),
	"Kulon Shield": ItemData(280, ItemClassification.filler),
	"Divine Barrier": ItemData(281, ItemClassification.filler),
	"Sniper Shield": ItemData(282, ItemClassification.filler),
	"Yin Yang Ward": ItemData(283, ItemClassification.filler),
	"Ronin Shield": ItemData(284, ItemClassification.filler),
	"Wild Shield": ItemData(285, ItemClassification.filler),
	"Brave Shield": ItemData(286, ItemClassification.filler),
	"Hazard Shield": ItemData(287, ItemClassification.filler),
	"Dramon Shield": ItemData(288, ItemClassification.filler),
	"Beam Shield": ItemData(289, ItemClassification.filler),
	"High Security": ItemData(290, ItemClassification.filler),
	"Apocalypse": ItemData(291, ItemClassification.filler),
	"Power Gem": ItemData(292, ItemClassification.filler),
	"Power Ring": ItemData(293, ItemClassification.filler),
	"Guard Gem": ItemData(294, ItemClassification.filler),
	"Guard Ring": ItemData(295, ItemClassification.filler),
	"Spirit Gem": ItemData(296, ItemClassification.filler),
	"Spirit Ring": ItemData(297, ItemClassification.filler),
	"Wisdom Gem": ItemData(298, ItemClassification.filler),
	"Wisdom Ring": ItemData(299, ItemClassification.filler),
	"Boost Gem": ItemData(300, ItemClassification.filler),
	"Boost Ring": ItemData(301, ItemClassification.filler),
	"Charisma Gem": ItemData(302, ItemClassification.filler),
	"Charisma Ring": ItemData(303, ItemClassification.filler),
	"Flame Ring": ItemData(304, ItemClassification.filler),
	"Water Ring": ItemData(305, ItemClassification.filler),
	"Ice Ring": ItemData(306, ItemClassification.filler),
	"Wind Ring": ItemData(307, ItemClassification.filler),
	"Thunder Ring": ItemData(308, ItemClassification.filler),
	"Machine Ring": ItemData(309, ItemClassification.filler),
	"Dark Ring": ItemData(310, ItemClassification.filler),
	"Antidote Ring": ItemData(311, ItemClassification.filler),
	"Revive Ring": ItemData(312, ItemClassification.filler),
	"Awake Ring": ItemData(313, ItemClassification.filler),
	"Sober Ring": ItemData(314, ItemClassification.filler),
	"Prayer Ring": ItemData(315, ItemClassification.filler),
	"Multi Crest": ItemData(316, ItemClassification.filler),
	"Search Crest": ItemData(317, ItemClassification.filler),
	"Counter Crest": ItemData(318, ItemClassification.filler),
	"Binder Crest": ItemData(319, ItemClassification.filler),
	"Recover Crest": ItemData(320, ItemClassification.filler),
	"EXP Adapter": ItemData(321, ItemClassification.filler),
	"BIT Adapter": ItemData(322, ItemClassification.filler),
	"MP Proxy": ItemData(323, ItemClassification.filler),
	"MP Mega Proxy": ItemData(324, ItemClassification.filler),
	"HP Proxy": ItemData(325, ItemClassification.filler),
	"HP Mega Proxy": ItemData(326, ItemClassification.filler),
	"Hack Sticker": ItemData(327, ItemClassification.filler),
	"Hack System": ItemData(328, ItemClassification.filler),
	"Over Clocked": ItemData(329, ItemClassification.filler),
	"Over Load": ItemData(330, ItemClassification.filler),
	"Glasses": ItemData(331, ItemClassification.filler),
	"Goggles": ItemData(332, ItemClassification.filler),
	"Dance Feather": ItemData(333, ItemClassification.filler),
	"Dance Wing": ItemData(334, ItemClassification.filler),
	"Runner Sandal": ItemData(335, ItemClassification.filler),
	"Runner Shoes": ItemData(336, ItemClassification.filler),
	"Training Book": ItemData(337, ItemClassification.filler),
	"Power Brace": ItemData(338, ItemClassification.filler),
	"Fire Power 1": ItemData(339, ItemClassification.filler),
	"Fire Power 2": ItemData(340, ItemClassification.filler),
	"Fire Power S": ItemData(341, ItemClassification.filler),
	"Water Power 1": ItemData(342, ItemClassification.filler),
	"Water Power 2": ItemData(343, ItemClassification.filler),
	"Water Power S": ItemData(344, ItemClassification.filler),
	"Ice Power 1": ItemData(345, ItemClassification.filler),
	"Ice Power 2": ItemData(346, ItemClassification.filler),
	"Ice Power S": ItemData(347, ItemClassification.filler),
	"Wind Power 1": ItemData(348, ItemClassification.filler),
	"Wind Power 2": ItemData(349, ItemClassification.filler),
	"Wind Power S": ItemData(350, ItemClassification.filler),
	"Bolt Power 1": ItemData(351, ItemClassification.filler),
	"Bolt Power 2": ItemData(352, ItemClassification.filler),
	"Bolt Power S": ItemData(353, ItemClassification.filler),
	"Metal Power 1": ItemData(354, ItemClassification.filler),
	"Metal Power 2": ItemData(355, ItemClassification.filler),
	"Metal Power S": ItemData(356, ItemClassification.filler),
	"Dark Power 1": ItemData(357, ItemClassification.filler),
	"Dark Power 2": ItemData(358, ItemClassification.filler),
	"Dark Power S": ItemData(359, ItemClassification.filler),
	"Monmon DDNA": ItemData(360, ItemClassification.filler),
	"Booster 02a": ItemData(361, ItemClassification.filler),
	"Booster 03a": ItemData(362, ItemClassification.filler),
	"Booster 04a": ItemData(363, ItemClassification.filler),
	"Booster 05a": ItemData(364, ItemClassification.filler),
	"Booster 06a": ItemData(365, ItemClassification.filler),
	"Booster 07a": ItemData(366, ItemClassification.filler),
	"Booster 08a": ItemData(367, ItemClassification.filler),
	"Booster 09a": ItemData(368, ItemClassification.filler),
	"Booster 10a": ItemData(369, ItemClassification.filler),
	"Booster 11a": ItemData(370, ItemClassification.filler),
	"Booster 12a": ItemData(371, ItemClassification.filler),
	"Booster 13a": ItemData(372, ItemClassification.filler),
	"Booster 14a": ItemData(373, ItemClassification.filler),
	"Booster 15a": ItemData(374, ItemClassification.filler),
	"Booster 1b": ItemData(375, ItemClassification.filler),
	"Booster 2b": ItemData(376, ItemClassification.filler),
	"Booster 3b": ItemData(377, ItemClassification.filler),
	"Booster 4b": ItemData(378, ItemClassification.filler),
	"Booster 5b": ItemData(379, ItemClassification.filler),
	"Booster 6b": ItemData(380, ItemClassification.filler),
	"Booster 7b": ItemData(381, ItemClassification.filler),
	"Booster 8b": ItemData(382, ItemClassification.filler),
	"Booster 9b": ItemData(383, ItemClassification.filler),
	"Booster 10b": ItemData(384, ItemClassification.filler),
	"Booster 11b": ItemData(385, ItemClassification.filler),
	"Booster 12b": ItemData(386, ItemClassification.filler),
	"Booster 13b": ItemData(387, ItemClassification.filler),
	"Booster 14b": ItemData(388, ItemClassification.filler),
	"Booster 15b": ItemData(389, ItemClassification.filler),
	"R-Booster 01": ItemData(390, ItemClassification.filler),
	"R-Booster 02": ItemData(391, ItemClassification.filler),
	"R-Booster 03": ItemData(392, ItemClassification.filler),
	"R-Booster 04": ItemData(393, ItemClassification.filler),
	"R-Booster 05": ItemData(394, ItemClassification.filler),
	"Kumamon DDNA": ItemData(395, ItemClassification.useful),
	"Crony ID": ItemData(396, ItemClassification.filler),
	# "Etemon's Mike": ItemData(397, ItemClassification.filler),
	"Blue Card": ItemData(398, ItemClassification.progression),
	# "8lue Card": ItemData(399, ItemClassification.filler),
	# "リカバリーCD3": ItemData(400, ItemClassification.filler),
	"Staff Pass": ItemData(401, ItemClassification.progression),
	"Folder Bag": ItemData(402, ItemClassification.skip_balancing)
}

ALL_ITEMS_TABLE: Dict[str, ItemData] = {}

i = 1
for item_name, data in ACTUAL_ITEMS.items():
    ALL_ITEMS_TABLE[item_name] = data
    i += 1


